// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACHkTHvjq3EdldSA0A98Q-kO5u7_jxhow',
    appId: '1:1032251770856:web:e77289463ecc807b2c865d',
    messagingSenderId: '1032251770856',
    projectId: 'auth-bba7a',
    authDomain: 'auth-bba7a.firebaseapp.com',
    storageBucket: 'auth-bba7a.appspot.com',
    measurementId: 'G-8FSRJK0K25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0IZXeS-DmrWznXiGH-Tj3jRfR_Yl-8g',
    appId: '1:1032251770856:android:f60c60062f992e882c865d',
    messagingSenderId: '1032251770856',
    projectId: 'auth-bba7a',
    storageBucket: 'auth-bba7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAH0NTZeG5Hg_ahmlPkO6J-qxhrgiWrDw',
    appId: '1:1032251770856:ios:20f5f339a38b881e2c865d',
    messagingSenderId: '1032251770856',
    projectId: 'auth-bba7a',
    storageBucket: 'auth-bba7a.appspot.com',
    iosClientId: '1032251770856-314esi92c7hk3ff8uekm8alqri5ve7tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAH0NTZeG5Hg_ahmlPkO6J-qxhrgiWrDw',
    appId: '1:1032251770856:ios:c724e6ce4198a9d92c865d',
    messagingSenderId: '1032251770856',
    projectId: 'auth-bba7a',
    storageBucket: 'auth-bba7a.appspot.com',
    iosClientId: '1032251770856-uobeehddun94jrgo0b81t2uho72p09lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth0.RunnerTests',
  );
}
